# docker/apache-hardening.conf  → /etc/apache2/conf-available/zz-mirza.conf
# SPDX-License-Identifier: AGPL-3.0-or-later
ServerName localhost
ServerTokens Prod
TraceEnable Off
Timeout 120
KeepAliveTimeout 10
FileETag None
<Files ".ht*">
    Require all denied
</Files>
